name: StarConvexSegmentation
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - setuptools
  - numpy
  - pip:
      - torch==2.5.1
      - torchvision==0.20.1
      - torchaudio==2.5.1
      - opencv-python==4.11.0.86
      - filelock==3.13.1
      - fsspec==2024.2.0
      - jinja2==3.1.3
      - markupsafe==2.1.5
      - mpmath==1.3.0
      - networkx==3.2.1
      - pillow==10.2.0
      - sympy==1.13.1
      - typing-extensions==4.9.0
