name: CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: 3.12
        environment-file: environment.yml
        auto-activate-base: false

    - name: Configure PYTHONPATH and Install Project
      shell: bash -l {0}
      run: |
        conda init bash
        source ~/.bashrc
        conda activate test
        # Export PYTHONPATH to include the root directory
        echo "PYTHONPATH=$(pwd):$PYTHONPATH" >> $GITHUB_ENV
        # Install the project in editable mode
        pip install -e .
        # Install additional tools
        pip install black isort flake8

    - name: Debug Environment
      shell: bash -l {0}
      run: |
        conda activate test
        conda env list
        conda info
        pip list

    - name: Check Code Formatting with Black
      shell: bash -l {0}
      run: |
        conda activate test
        black .

    - name: Check Import Sorting with isort
      shell: bash -l {0}
      run: |
        conda activate test
        isort .

    - name: Lint Code with Flake8
      shell: bash -l {0}
      run: |
        conda activate test
        flake8 . || echo "Flake8 found issues, but the CI will not fail."

    - name: Run Tests
      shell: bash -l {0}
      run: |
        conda activate test
        pytest
