name: CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: 3.12
        environment-file: environment.yml
        auto-activate-base: false

    - name: Configure PYTHONPATH and Install Project
      shell: bash -l {0}
      run: |
        conda init bash
        source ~/.bashrc
        conda activate test
        # Export PYTHONPATH to include the root directory
        echo "PYTHONPATH=$(pwd):$PYTHONPATH" >> $GITHUB_ENV
        # Install the project in editable mode
        pip install -e .
        # Install additional tools
        pip install black isort yapf pytest pytest-cov

    - name: Debug Environment
      shell: bash -l {0}
      run: |
        conda activate test
        conda env list
        conda info
        pip list

    - name: Check Code Formatting with Black
      shell: bash -l {0}
      run: |
        conda activate test
        black .

    - name: Check Import Sorting with isort
      shell: bash -l {0}
      run: |
        conda activate test
        isort .

    - name: Format Code with YAPF
      shell: bash -l {0}
      run: |
        conda activate test
        yapf -ir .

    - name: Run Tests with Coverage
      shell: bash -l {0}
      run: |
        conda activate test
        pytest --cov=./ --cov-report=xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false