name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: 3.12
        environment-file: environment.yml
        auto-activate-base: false

    - name: Run tests
      run: |
        conda activate StarConvexSegmentation
        pytest
